name: Build and Publish

on:
  # run it on push to the default repository branch
  push:
    branches: [create-exe]
  # run it during pull request
  pull_request:

jobs:
  create_exec:
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller main.py
    - uses: actions/upload-artifact@v3
      with:
        path: dist/*

#  create_exec:
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v2
#
#    - name: Package Application
#      uses: JackMcKew/pyinstaller-action-windows@main
#      with:
#        path: .
#
#    - uses: actions/upload-artifact@v2
#      with:
#        name: splinterlands-stats
#        path: src/dist/windows

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push  splinterlands-stats docker image
        run: |
               docker build . --tag ghcr.io/gamerbeaker007/splinterlands-stats:latest
               docker push ghcr.io/gamerbeaker007/splinterlands-stats:latest
