name: Build and Publish

on:
  # run it on push to the default repository branch
  push:
    branches:
      - 'main'
      - 'build_*'
  # run it during pull request
  pull_request:

env:
  output_dir: 'splinterlands-stats'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest'] # later add others like 'ubuntu-latest', 'macos-latest'

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller --onefile --distpath $output_dir main.py
    - run: cp -r "output/" "$output_dir/"
    - run: cp "config.properties" "$output_dir/"

    - if: matrix.os == 'ubuntu-latest'
      run: |
        mv "$output_dir/main" "$output_dir/main.sh"
        tar -cvf spl-stats.tar $output_dir

    - if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v3
      with:
        name: splinterlands-stats-${{ matrix.os }}
        path: spl-stats.tar

    - if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v3
      with:
        name: splinterlands-stats-${{ matrix.os }}
        path: $output_dir/*


  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push  splinterlands-stats docker image
        run: |
               docker build . --tag ghcr.io/gamerbeaker007/splinterlands-stats:latest
               docker push ghcr.io/gamerbeaker007/splinterlands-stats:latest
